var tigger = { character: "Tigger" }; 
var pooh = { character: "Winnie the Pooh" };
var piglet = { character: "Piglet"};
var eeyore = { character: "Eeyore"};        
var heffa = { character: "Heffalumps"};  
var kanga = { character: "Kanga"};        
var chris = { character: "Christopher Robin"};
var rabbit = { character: "Rabbit"};
var bees = { character: "Bees"};
var owl = { character: "Owl"};
var gopher = { character: "Gopher"};

heffa.west = eeyore;
eeyore.south = kanga;
chris.north = eeyore.south;
chris.west = owl;
chris.east = rabbit;
chris.south = pooh;
gopher.west = chris.east;
tigger.north = chris.south
pooh.west = piglet;
pooh.east = bees;
bees.north = chris.east;
piglet.north= chris.west;
